// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dapcdotgrifltlovexwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhcGNkb3RncmlmbHRsb3ZleHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTgwMDEsImV4cCI6MjA2Nzc3NDAwMX0.3SV_hsYKl5ki_vipXxUbhzXvO_A0CcAxZMb7dcqHQ4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});